version: "3"
services:
  frontEnd:
    image: pdf-frontend
    container_name: frontEnd
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./
        target: /app/upload
  express:
    image: pdf-frontend-express
    container_name: express
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app/upload
  flask:
    image: pdf-backend
    container_name: flask
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./
        target: /work/upload